"""added system messages

Revision ID: 0f4f35a58895
Revises: 278159d4fca1
Create Date: 2024-10-19 19:56:39.339226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f4f35a58895'
down_revision: Union[str, None] = '278159d4fca1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('sys_msg', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'sys_msg')
    # ### end Alembic commands ###
